services:
  triton:
    image: nvcr.io/nvidia/tritonserver:24.11-py3
    command: tritonserver --model-repository=/models
    build:
      context: .
      dockerfile: Dockerfile_triton
    volumes:
      - ./model_repository_python:/models
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile_flask
    ports:
      - "5000:5000"
    depends_on:
      - triton