# Base image
FROM nvcr.io/nvidia/tritonserver:24.11-py3

## Install base utilities for miniconda
#RUN apt-get update \
#  && apt-get install -y build-essential \
#  && apt-get install -y wget \
#  && apt-get install -y nvidia-container-toolkit \
#  && apt-get clean \
#  && rm -rf /var/lib/apt/lists/*
#
## Install miniconda
#ENV CONDA_DIR=/opt/conda
#RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh -O ~/miniconda.sh && \
# /bin/bash ~/miniconda.sh -b -p /opt/conda
#
## Put conda in path so we can use conda activate
#ENV PATH=$CONDA_DIR/bin:$PATH
#
## Create the environment
#COPY environment.yml /usr/src/app/
#RUN conda env create -f /usr/src/app/environment.yml
#
## Make RUN commands use the new environment
#SHELL ["conda", "run", "-n", "itt", "/bin/bash", "-c"]

# install Python modules needed by the Python app
RUN apt-get update \
    && apt-get remove -y python3-blinker \
    && apt-get install -y nvidia-container-toolkit \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt
