# our base image
FROM continuumio/miniconda3

RUN apt-get update \
  && apt-get install -y build-essential \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Create the environment:
COPY environment.yml /usr/src/app/
RUN conda env create -f /usr/src/app/environment.yml

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "itt", "/bin/bash", "-c"]

# install Python modules needed by the Python app
COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt

# copy files required for the app to run
COPY src /usr/src/app/

# tell the port number the container should expose
EXPOSE 5000

# run the application
ENV FLASK_ENV=development
ENV FLASK_DEBUG=1
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "itt", "python", "/usr/src/app/app_triton_python.py"]